<?php return [
    'adminAllowed' => [
        'bottomMenu',
        'connectedFile',
        'dashboard',
        'deliveryTypeField',
        'deliveryTypePaymentMethod',
        'feedbackAnswer',
        'headerContent',
        'leftColumn',
        'newsmailGroup',
        'categoryIcon',
        'productIcon',
        'productSearchParameter',
        'registrationField',
        'registrationUserGroup',
        'rightColumn',
        'structure',
        'mobileMenu',
        'collectionProduct',
        'collections',
    ],
    'publicAllowed' => [
        'bannerCategoryBanner',
        'bottomMenu',
        'commentTarget',
        'connectedFile',
        'feedbackAnswer',
        'headerContent',
        'leftColumn',
        'newsmailGroup',
        'registrationField',
        'registrationUserGroup',
        'rightColumn',
        'structure',
        'mobileMenu',
    ],
];