ALTER TABLE `engine_zxitem_language` CHANGE `value` `value` ENUM(
            "be",
            "bs",
            "by",
            "ca",
            "cs",
            "cz",
            "da",
            "de",
            "el",
            "en",
            "eo",
            "es",
            "eu",
            "fi",
            "fr",
            "gl",
            "hr",
            "hu",
            "is",
            "it",
            "la",
            "lt",
            "lv",
            "m-",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "ru",
            "sh",
            "sk",
            "sl",
            "sr",
            "sv",
            "tr"
        ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 
	
	
	OPTIMIZE TABLE `engine_zxitem_language` ;
	
	

ALTER TABLE `engine_structure_links` CHANGE `type` `type` ENUM(
    'type',
    'adFilesSelector',
    'authorMusic',
    'authorPicture',
    'authorsCatalogue',
    'ayTrack',
    'bannerCategoryBanner',
    'cityLink',
    'commentTarget',
    'compilation',
    'connectedFile',
    'countries',
    'countryLink',
    'displayinmenu',
    'displayinmenumobile',
    'feedbackAnswer',
    'foreignRelative',
    'gameLink',
    'groupsCatalogue',
    'groupSub',
    'headerContent',
    'infoFilesSelector',
    'inlayFilesSelector',
    'mapFilesSelector',
    'mobileMenu',
    'newsmailGroup',
    'partiesCatalogue',
    'partyMusic',
    'partyPicture',
    'partyProd',
    'playlist',
    'registrationField',
    'registrationUserGroup',
    'rightColumn',
    'rzx',
    'screenshotsSelector',
    'softCatalogue',
    'structure',
    'submenulist',
    'tagLink',
    'tagsList',
    'userRelation',
    'zxProdCategory',
    'zxProdGroups',
    'zxProdPublishers',
    'zxReleasePublishers'
   
) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 

	OPTIMIZE TABLE `engine_structure_links` ;


ALTER TABLE `engine_module_zxrelease_hw_required` CHANGE `value` `value` ENUM(
"3dos",
"3dosdisk",
"atm",
"atm2",
"atmide",
"ay",
"aymouse",
"baseconf",
"beeper",
"betadisk",
"byte",
"cache",
"cd",
"cheetah",
"covox",
"cpm",
"cursor",
"divide",
"divmmc",
"divsd",
"dmausc",
"elementzxmb",
"esxdos",
"flashcolor",
"gmx",
"gs",
"int2_1",
"int2_2",
"isdos",
"kempston",
"kempston8b",
"kempstonmouse",
"mdos",
"nedoos",
"nemoide",
"ngs",
"pentagon1024",
"pentagon128",
"pentagon2666",
"pentagon512",
"profi",
"profiide",
"saa",
"samcoupe",
"scorpion",
"scorpion1024",
"sid",
"sinclairql",
"smuc",
"soundrive",
"specdrum",
"tape",
"timex2048",
"timex2068",
"trdos",
"ts",
"tsconf",
"tsfm",
"ulaplus",
"zcontroller",
"zx128",
"zx128+2",
"zx128+2b",
"zx128+3",
"zx16",
"zx48",
"zx80",
"zx811",
"zx8116",
"zx812",
"zx8132",
"zx8164",
"zxevolution",
"zxm",
"zxmphoenix",
"zxnext",
"zxpand",
"zxuno"

) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 


ALTER TABLE `engine_module_zxrelease` CHANGE `denyVoting` `denyVoting` TINYINT NOT NULL; 
ALTER TABLE `engine_module_zxrelease` CHANGE `denyComments` `denyComments` TINYINT NOT NULL; 
ALTER TABLE `engine_module_zxrelease` CHANGE `year` `year` SMALLINT NOT NULL; 

ALTER TABLE `engine_module_zxrelease` CHANGE `releaseType` `releaseType` ENUM(
 'unknown',
            'original',
            'rerelease',
            'adaptation',
            'localization',
            'mod',
            'crack',
            'mia',
            'corrupted',
            'compilation',
            'incomplete',
            'demoversion'
) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 
	   