-- Hardware catalog: move the hardware list out of the `value` ENUM into its own
-- table with localized names, and normalize the release link table to ids.
--
-- Step 0 is mandatory and must run first: the ENUM lists 'aymouse' twice, and
-- MariaDB refuses ANY rebuild of the column while that is true (ERROR 1291) --
-- including ADD COLUMN, ENGINE=InnoDB, CREATE TABLE ... LIKE and mysqldump
-- reload. Rewriting the column definition as VARCHAR drops the duplicate.
--
-- After this migration `value` no longer exists; hardware is referenced by
-- `hardwareId`. Codes remain the contract everywhere above the database
-- (element properties, forms, REST DTOs, the public /api/ filters).

-- Step 0 --------------------------------------------------------------------
ALTER TABLE `engine_module_zxrelease_hw_required` MODIFY `value` VARCHAR(32) NOT NULL;

-- Step 1: clean the link table ----------------------------------------------
-- rows whose release no longer exists (3638 at the time of writing)
DELETE `l` FROM `engine_module_zxrelease_hw_required` `l`
    LEFT JOIN `engine_module_zxrelease` `r` ON `r`.`id` = `l`.`elementId`
WHERE `r`.`id` IS NULL;

-- duplicate (elementId, value) pairs (189), keeping the lowest id of each
DELETE `a` FROM `engine_module_zxrelease_hw_required` `a`
    JOIN `engine_module_zxrelease_hw_required` `b`
        ON `b`.`elementId` = `a`.`elementId` AND `b`.`value` = `a`.`value` AND `b`.`id` < `a`.`id`;

-- Step 2: the catalog --------------------------------------------------------
CREATE TABLE `engine_hardware`
(
    `id`       INT UNSIGNED                                                                  NOT NULL AUTO_INCREMENT,
    `code`     VARCHAR(32)                                                                   NOT NULL,
    `category` ENUM ('computers','storage','dos','sound','controls','expansion')             NOT NULL,
    `position` INT                                                                           NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `code` (`code`),
    KEY `category` (`category`, `position`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `engine_hardware_name`
(
    `hardwareId`   INT UNSIGNED NOT NULL,
    `languageCode` CHAR(2)      NOT NULL,
    `name`         VARCHAR(255) NOT NULL,
    `shortName`    VARCHAR(255) NOT NULL,
    PRIMARY KEY (`hardwareId`, `languageCode`),
    CONSTRAINT `hardware_name_hardware` FOREIGN KEY (`hardwareId`) REFERENCES `engine_hardware` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Seed: 122 codes. Category and display order come from ZxArt\Hardware\HardwareCatalog,
-- names from the SPA translations that owned them until now. `covox` (0 rows),
-- `hdd` and `alf1` (translation-only keys) are deliberately not seeded.
-- `zxevolution` has live rows but never had a HardwareItem case; `samdos`, `gdos`
-- and `mb02` are new. Languages are ISO 639-1 codes, matching
-- ZxArt\Shared\InterfaceLanguage and the SPA translation files.
INSERT INTO `engine_hardware` (`id`, `code`, `category`, `position`) VALUES
(1, 'zx48', 'computers', 0),
(2, 'zx16', 'computers', 1),
(3, 'zx128', 'computers', 2),
(4, 'zx128+2', 'computers', 3),
(5, 'zx128+2b', 'computers', 4),
(6, 'zx128+3', 'computers', 5),
(7, 'sinclairql', 'computers', 6),
(8, 'timex2048', 'computers', 7),
(9, 'timex2068', 'computers', 8),
(10, 'atm', 'computers', 9),
(11, 'atm2', 'computers', 10),
(12, 'pentagon128', 'computers', 11),
(13, 'pentagon512', 'computers', 12),
(14, 'pentagon1024', 'computers', 13),
(15, 'pentagon2666', 'computers', 14),
(16, 'profi', 'computers', 15),
(17, 'scorpion', 'computers', 16),
(18, 'scorpion1024', 'computers', 17),
(19, 'byte', 'computers', 18),
(20, 'zxmphoenix', 'computers', 19),
(21, 'baseconf', 'computers', 20),
(22, 'tsconf', 'computers', 21),
(23, 'zxnext', 'computers', 22),
(24, 'elementzxmb', 'computers', 23),
(25, 'zxuno', 'computers', 24),
(26, 'samcoupe', 'computers', 25),
(27, 'zx80', 'computers', 26),
(28, 'zx8116', 'computers', 27),
(29, 'zx811', 'computers', 28),
(30, 'zx812', 'computers', 29),
(31, 'zx8132', 'computers', 30),
(32, 'zx8164', 'computers', 31),
(33, 'lambda8300', 'computers', 32),
(34, 'sprinter', 'computers', 33),
(35, 'alf', 'computers', 34),
(36, 'didaktik80', 'computers', 35),
(37, 'tk9x', 'computers', 36),
(38, 'zxevolution', 'computers', 37),
(39, 'tape', 'storage', 38),
(40, '3dosdisk', 'storage', 39),
(41, 'betadisk', 'storage', 40),
(42, 'cd', 'storage', 41),
(43, 'profiide', 'storage', 42),
(44, 'nemoide', 'storage', 43),
(45, 'zcontroller', 'storage', 44),
(46, 'atmide', 'storage', 45),
(47, 'divide', 'storage', 46),
(48, 'divmmc', 'storage', 47),
(49, 'smuc', 'storage', 48),
(50, 'sddivmmc', 'storage', 49),
(51, 'sdz', 'storage', 50),
(52, 'sdneogs', 'storage', 51),
(53, 'atom', 'storage', 52),
(54, 'atom_lite', 'storage', 53),
(55, 'microdrive', 'storage', 54),
(56, 'i2cartridge', 'storage', 55),
(57, 'dandanator', 'storage', 56),
(58, 'timex_cartridge', 'storage', 57),
(59, 'mb02', 'storage', 58),
(60, 'trdos4x', 'dos', 59),
(61, 'trdos', 'dos', 60),
(62, 'isdos', 'dos', 61),
(63, 'tasis', 'dos', 62),
(64, 'cpm', 'dos', 63),
(65, 'esxdos', 'dos', 64),
(66, 'mdos', 'dos', 65),
(67, '3dos', 'dos', 66),
(68, 'nedoos', 'dos', 67),
(69, 'opd', 'dos', 68),
(70, 'disciple', 'dos', 69),
(71, 'tos', 'dos', 70),
(72, 'bsdos', 'dos', 71),
(73, 'samdos', 'dos', 72),
(74, 'gdos', 'dos', 73),
(75, 'ay', 'sound', 74),
(76, 'beeper', 'sound', 75),
(77, 'ts', 'sound', 76),
(78, 'tsfm', 'sound', 77),
(79, 'aynext', 'sound', 78),
(80, 'nextdac', 'sound', 79),
(81, 'gs', 'sound', 80),
(82, 'ngs', 'sound', 81),
(83, 'covoxfb', 'sound', 82),
(84, 'covoxdd', 'sound', 83),
(85, 'covoxgs', 'sound', 84),
(86, 'soundrive', 'sound', 85),
(87, 'specdrum', 'sound', 86),
(88, 'cheetah', 'sound', 87),
(89, 'dmausc', 'sound', 88),
(90, 'saa', 'sound', 89),
(91, 'zxm', 'sound', 90),
(92, 'sid', 'sound', 91),
(93, 'sidelzx', 'sound', 92),
(94, 'quazar_surround', 'sound', 93),
(95, 'midi', 'sound', 94),
(96, 'cursor', 'controls', 95),
(97, 'kempston', 'controls', 96),
(98, 'kempston8b', 'controls', 97),
(99, 'int2_1', 'controls', 98),
(100, 'int2_2', 'controls', 99),
(101, 'kempstonmouse', 'controls', 100),
(102, 'aymouse', 'controls', 101),
(103, 'amigamouse', 'controls', 102),
(104, 'atarimouse', 'controls', 103),
(105, 'amxmouse', 'controls', 104),
(106, 'sammouse', 'controls', 105),
(107, 'gunstick', 'controls', 106),
(108, 'magnumlight', 'controls', 107),
(109, 'novina', 'controls', 108),
(110, 'lightpen', 'controls', 109),
(111, 'defender', 'controls', 110),
(112, 'zxpand', 'expansion', 111),
(113, 'cache', 'expansion', 112),
(114, 'gmx', 'expansion', 113),
(115, 'flashcolor', 'expansion', 114),
(116, 'ulaplus', 'expansion', 115),
(117, 'radastan', 'expansion', 116),
(118, 'dma', 'expansion', 117),
(119, 'chroma81', 'expansion', 118),
(120, 'trinity', 'expansion', 119),
(121, 'hires', 'expansion', 120),
(122, 'hgfx', 'expansion', 121);

INSERT INTO `engine_hardware_name` (`hardwareId`, `languageCode`, `name`, `shortName`) VALUES
(1, 'en', 'ZX Spectrum 48K', '48'),
(1, 'ru', 'ZX Spectrum 48K', '48'),
(1, 'es', 'ZX Spectrum 48K', '48'),
(2, 'en', 'ZX Spectrum 16K', '16'),
(2, 'ru', 'ZX Spectrum 16K', '16'),
(2, 'es', 'ZX Spectrum 16K', '16'),
(3, 'en', 'ZX Spectrum 128K', '128'),
(3, 'ru', 'ZX Spectrum 128K', '128'),
(3, 'es', 'ZX Spectrum 128K', '128'),
(4, 'en', 'ZX Spectrum 128 +2', '128+2'),
(4, 'ru', 'ZX Spectrum 128 +2', '128+2'),
(4, 'es', 'ZX Spectrum 128 +2', '128+2'),
(5, 'en', 'ZX Spectrum 128 +2b', '128+2b'),
(5, 'ru', 'ZX Spectrum 128 +2b', '128+2b'),
(5, 'es', 'ZX Spectrum 128 +2b', '128+2b'),
(6, 'en', 'ZX Spectrum 128 +3', '128+3'),
(6, 'ru', 'ZX Spectrum 128 +3', '128+3'),
(6, 'es', 'ZX Spectrum 128 +3', '128+3'),
(7, 'en', 'Sinclair QL', 'Sinclair QL'),
(7, 'ru', 'Sinclair QL', 'Sinclair QL'),
(7, 'es', 'Sinclair QL', 'Sinclair QL'),
(8, 'en', 'Timex TC2048', 'Timex TC2048'),
(8, 'ru', 'Timex TC2048', 'Timex TC2048'),
(8, 'es', 'Timex TC2048', 'Timex TC2048'),
(9, 'en', 'Timex Tx2068', 'Timex Tx2068'),
(9, 'ru', 'Timex Tx2068', 'Timex Tx2068'),
(9, 'es', 'Timex Tx2068', 'Timex Tx2068'),
(10, 'en', 'ATM', 'ATM'),
(10, 'ru', 'ATM', 'ATM'),
(10, 'es', 'ATM', 'ATM'),
(11, 'en', 'ATM Turbo 2/2+', 'ATM2'),
(11, 'ru', 'ATM Turbo 2/2+', 'ATM2'),
(11, 'es', 'ATM Turbo 2/2+', 'ATM2'),
(12, 'en', 'Pentagon 128', 'Pent128'),
(12, 'ru', 'Pentagon 128', 'Pent128'),
(12, 'es', 'Pentagon 128', 'Pent128'),
(13, 'en', 'Pentagon 512', 'Pent512'),
(13, 'ru', 'Pentagon 512', 'Pent512'),
(13, 'es', 'Pentagon 512', 'Pent512'),
(14, 'en', 'Pentagon 1024', 'Pent1024'),
(14, 'ru', 'Pentagon 1024', 'Pent1024'),
(14, 'es', 'Pentagon 1024', 'Pent1024'),
(15, 'en', 'Pentagon v2.666', 'Pent2.666'),
(15, 'ru', 'Pentagon v2.666', 'Pent2.666'),
(15, 'es', 'Pentagon v2.666', 'Pent2.666'),
(16, 'en', 'Profi', 'Profi'),
(16, 'ru', 'Profi', 'Profi'),
(16, 'es', 'Profi', 'Profi'),
(17, 'en', 'Scorpion', 'Scorp'),
(17, 'ru', 'Scorpion', 'Скорп'),
(17, 'es', 'Scorpion', 'Scorp'),
(18, 'en', 'Scorpion 1024', 'Scorp 1024'),
(18, 'ru', 'Скорпион 1024', 'Скорп 1024'),
(18, 'es', 'Scorpion 1024', 'Scorp 1024'),
(19, 'en', 'Byte/Byte-01', 'Byte/Byte-01'),
(19, 'ru', 'Байт/Байт-01', 'Байт/Байт-01'),
(19, 'es', 'Byte/Byte-01', 'Byte/Byte-01'),
(20, 'en', 'ZXM-Phoenix', 'ZXM-Phoenix'),
(20, 'ru', 'ZXM-Phoenix', 'ZXM-Phoenix'),
(20, 'es', 'ZXM-Phoenix', 'ZXM-Phoenix'),
(21, 'en', 'ZX Evolution BaseConf', 'Baseconf'),
(21, 'ru', 'ZX Evolution BaseConf', 'Baseconf'),
(21, 'es', 'ZX Evolution BaseConf', 'Baseconf'),
(22, 'en', 'ZX Evolution TS-Conf', 'TS-Conf'),
(22, 'ru', 'ZX Evolution TS-Conf', 'TS-Conf'),
(22, 'es', 'ZX Evolution TS-Conf', 'TS-Conf'),
(23, 'en', 'ZX Spectrum Next', 'Next'),
(23, 'ru', 'ZX Spectrum Next', 'Next'),
(23, 'es', 'ZX Spectrum Next', 'Next'),
(24, 'en', 'eLeMeNt ZX/MB', 'eZX/MB'),
(24, 'ru', 'eLeMeNt ZX/MB', 'eZX/MB'),
(24, 'es', 'eLeMeNt ZX/MB', 'eZX/MB'),
(25, 'en', 'ZX-Uno', 'ZX-Uno'),
(25, 'ru', 'ZX-Uno', 'ZX-Uno'),
(25, 'es', 'ZX-Uno', 'ZX-Uno'),
(26, 'en', 'SAM Coupé', 'SAM Coupé'),
(26, 'ru', 'SAM Coupé', 'SAM Coupé'),
(26, 'es', 'SAM Coupé', 'SAM Coupé'),
(27, 'en', 'ZX80', 'ZX80'),
(27, 'ru', 'ZX80', 'ZX80'),
(27, 'es', 'ZX80', 'ZX80'),
(28, 'en', 'ZX81 16K', 'ZX81 16K'),
(28, 'ru', 'ZX81 16K', 'ZX81 16K'),
(28, 'es', 'ZX81 16K', 'ZX81 16K'),
(29, 'en', 'ZX81 1K', 'ZX81 1K'),
(29, 'ru', 'ZX81 1K', 'ZX81 1K'),
(29, 'es', 'ZX81 1K', 'ZX81 1K'),
(30, 'en', 'ZX81 2K', 'ZX81 2K'),
(30, 'ru', 'ZX81 2K', 'ZX81 2K'),
(30, 'es', 'ZX81 2K', 'ZX81 2K'),
(31, 'en', 'ZX81 32K', 'ZX81 32K'),
(31, 'ru', 'ZX81 32K', 'ZX81 32K'),
(31, 'es', 'ZX81 32K', 'ZX81 32K'),
(32, 'en', 'ZX81 64K', 'ZX81 64K'),
(32, 'ru', 'ZX81 64K', 'ZX81 64K'),
(32, 'es', 'ZX81 64K', 'ZX81 64K'),
(33, 'en', 'Lambda 8300', 'Lambda 8300'),
(33, 'ru', 'Lambda 8300', 'Lambda 8300'),
(33, 'es', 'Lambda 8300', 'Lambda 8300'),
(34, 'en', 'Sprinter', 'Spr'),
(34, 'ru', 'Спринтер', 'Спр'),
(34, 'es', 'Sprinter', 'Spr'),
(35, 'en', 'ALF TV Game', 'ALF'),
(35, 'ru', 'Приставка "Эльф"', 'Эльф'),
(35, 'es', 'Juego de televisión ALF', 'ALF'),
(36, 'en', 'Didaktik Gama', 'Didaktik Gama'),
(36, 'ru', 'Didaktik Gama', 'Didaktik Gama'),
(36, 'es', 'Didaktik Gama', 'Didaktik Gama'),
(37, 'en', 'TK-90x/TK-95x', 'TK-90x/TK-95x'),
(37, 'ru', 'TK-90x/TK-95x', 'TK-90x/TK-95x'),
(37, 'es', 'TK-90x/TK-95x', 'TK-90x/TK-95x'),
(38, 'en', 'ZX Evolution', 'Evo'),
(38, 'ru', 'ZX Evolution', 'Evo'),
(38, 'es', 'ZX Evolution', 'Evo'),
(39, 'en', 'Tape', 'Tape'),
(39, 'ru', 'Магнитная лента', 'Магнитная лента'),
(39, 'es', 'Cinta', 'Cinta'),
(40, 'en', '+3DOS Disk system', '+3DOS Disk system'),
(40, 'ru', 'Дисковод +3DOS', 'Дисковод +3DOS'),
(40, 'es', 'Sistema de disco +3DOS', 'Sistema de disco +3DOS'),
(41, 'en', 'Beta Disk Interface', 'Beta Disk Interface'),
(41, 'ru', 'Beta Disk интерфейс', 'Beta Disk интерфейс'),
(41, 'es', 'Interfaz de Beta Disk', 'Interfaz de Beta Disk'),
(42, 'en', 'CD', 'CD'),
(42, 'ru', 'CD', 'CD'),
(42, 'es', 'CD', 'CD'),
(43, 'en', 'Profi IDE', 'Profi IDE'),
(43, 'ru', 'Profi IDE', 'Profi IDE'),
(43, 'es', 'Profi IDE', 'Profi IDE'),
(44, 'en', 'Nemo IDE', 'Nemo IDE'),
(44, 'ru', 'Nemo IDE', 'Nemo IDE'),
(44, 'es', 'Nemo IDE', 'Nemo IDE'),
(45, 'en', 'Z-Controller', 'Z-Controller'),
(45, 'ru', 'Z-Controller', 'Z-Controller'),
(45, 'es', 'Z-Controller', 'Z-Controller'),
(46, 'en', 'ATM IDE', 'ATM IDE'),
(46, 'ru', 'ATM IDE', 'ATM IDE'),
(46, 'es', 'ATM IDE', 'ATM IDE'),
(47, 'en', 'divIDE', 'divIDE'),
(47, 'ru', 'divIDE', 'divIDE'),
(47, 'es', 'divIDE', 'divIDE'),
(48, 'en', 'divMMC', 'divMMC'),
(48, 'ru', 'divMMC', 'divMMC'),
(48, 'es', 'divMMC', 'divMMC'),
(49, 'en', 'SMUC', 'SMUC'),
(49, 'ru', 'SMUC', 'SMUC'),
(49, 'es', 'SMUC', 'SMUC'),
(50, 'en', 'SD (DivMMC)', 'SD (DivMMC)'),
(50, 'ru', 'SD (DivMMC)', 'SD (DivMMC)'),
(50, 'es', 'SD (DivMMC)', 'SD (DivMMC)'),
(51, 'en', 'SD (Z-Controller)', 'SD (Z-Controller)'),
(51, 'ru', 'SD (Z-Controller)', 'SD (Z-Controller)'),
(51, 'es', 'SD (Z-Controller)', 'SD (Z-Controller)'),
(52, 'en', 'SD (NeoGS)', 'SD (NeoGS)'),
(52, 'ru', 'SD (NeoGS)', 'SD (NeoGS)'),
(52, 'es', 'SD (NeoGS)', 'SD (NeoGS)'),
(53, 'en', 'Atom', 'Atom'),
(53, 'ru', 'Atom', 'Atom'),
(53, 'es', 'Atom', 'Atom'),
(54, 'en', 'Atom Lite', 'Atom Lite'),
(54, 'ru', 'Atom Lite', 'Atom Lite'),
(54, 'es', 'Atom Lite', 'Atom Lite'),
(55, 'en', 'Microdrive', 'Microdrive'),
(55, 'ru', 'Microdrive', 'Microdrive'),
(55, 'es', 'Microdrive', 'Microdrive'),
(56, 'en', 'ZX Interface 2 Cartridge', 'ZX Interface 2 Cartridge'),
(56, 'ru', 'Картридж ZX Interface 2', 'Картридж ZX Interface 2'),
(56, 'es', 'Cartucho de ZX Interface 2', 'Cartucho de ZX Interface 2'),
(57, 'en', 'ZX Dandanator', 'ZX Dandanator'),
(57, 'ru', 'ZX Dandanator', 'ZX Dandanator'),
(57, 'es', 'ZX Dandanator', 'ZX Dandanator'),
(58, 'en', 'Timex Cartridge', 'Timex Cartridge'),
(58, 'ru', 'Timex Cartridge', 'Timex Cartridge'),
(58, 'es', 'Timex Cartridge', 'Timex Cartridge'),
(59, 'en', 'MB-02+', 'MB-02'),
(59, 'ru', 'MB-02+', 'MB-02'),
(59, 'es', 'MB-02+', 'MB-02'),
(60, 'en', 'TR-DOS 4.x', 'TR-DOS 4.x'),
(60, 'ru', 'TR-DOS 4.x', 'TR-DOS 4.x'),
(60, 'es', 'TR-DOS 4.x', 'TR-DOS 4.x'),
(61, 'en', 'TR-DOS 5.x', 'TR-DOS'),
(61, 'ru', 'TR-DOS 5.x', 'TR-DOS'),
(61, 'es', 'TR-DOS 5.x', 'TR-DOS'),
(62, 'en', 'iS-DOS', 'iS-DOS'),
(62, 'ru', 'iS-DOS', 'iS-DOS'),
(62, 'es', 'iS-DOS', 'iS-DOS'),
(63, 'en', 'OS TASiS', 'TASiS'),
(63, 'ru', 'ОС TASiS', 'TASiS'),
(63, 'es', 'OS TASiS', 'TASiS'),
(64, 'en', 'CP/M', 'CP/M'),
(64, 'ru', 'CP/M', 'CP/M'),
(64, 'es', 'CP/M', 'CP/M'),
(65, 'en', 'esxDOS', 'esxDOS'),
(65, 'ru', 'esxDOS', 'esxDOS'),
(65, 'es', 'esxDOS', 'esxDOS'),
(66, 'en', 'MDOS', 'MDOS'),
(66, 'ru', 'MDOS', 'MDOS'),
(66, 'es', 'MDOS', 'MDOS'),
(67, 'en', '+3DOS', '+3DOS'),
(67, 'ru', '+3DOS', '+3DOS'),
(67, 'es', '+3DOS', '+3DOS'),
(68, 'en', 'NedoOS', 'NedoOS'),
(68, 'ru', 'NedoOS', 'NedoOS'),
(68, 'es', 'NedoOS', 'NedoOS'),
(69, 'en', 'Opus Discovery', 'OPD'),
(69, 'ru', 'Opus Discovery', 'OPD'),
(69, 'es', 'Opus Discovery', 'OPD'),
(70, 'en', 'DISCiPLE', 'DISCiPLE'),
(70, 'ru', 'DISCiPLE', 'DISCiPLE'),
(70, 'es', 'DISCiPLE', 'DISCiPLE'),
(71, 'en', 'TOS (FDD3000)', 'TOS (FDD3000)'),
(71, 'ru', 'TOS (FDD3000)', 'TOS (FDD3000)'),
(71, 'es', 'TOS (FDD3000)', 'TOS (FDD3000)'),
(72, 'en', 'BSDOS', 'BSDOS'),
(72, 'ru', 'BSDOS', 'BSDOS'),
(72, 'es', 'BSDOS', 'BSDOS'),
(73, 'en', 'SAMDOS', 'SAMDOS'),
(73, 'ru', 'SAMDOS', 'SAMDOS'),
(73, 'es', 'SAMDOS', 'SAMDOS'),
(74, 'en', 'G+DOS (DISCiPLE / +D)', 'G+DOS'),
(74, 'ru', 'G+DOS (DISCiPLE / +D)', 'G+DOS'),
(74, 'es', 'G+DOS (DISCiPLE / +D)', 'G+DOS'),
(75, 'en', 'AY-3-8910/12, YM2149F', 'AY/YM'),
(75, 'ru', 'AY-3-8910/12, YM2149F', 'AY/YM'),
(75, 'es', 'AY-3-8910/12, YM2149F', 'AY/YM'),
(76, 'en', 'Beeper', 'Beeper'),
(76, 'ru', 'Бипер', 'Бипер'),
(76, 'es', 'Beeper', 'Beeper'),
(77, 'en', 'Turbo Sound', 'TS'),
(77, 'ru', 'Turbo Sound', 'TS'),
(77, 'es', 'Turbo Sound', 'TS'),
(78, 'en', 'Turbo Sound FM', 'TSFM'),
(78, 'ru', 'Turbo Sound FM', 'TSFM'),
(78, 'es', 'Turbo Sound FM', 'TSFM'),
(79, 'en', 'Turbo Sound Next', 'Turbo Sound Next'),
(79, 'ru', 'Turbo Sound Next', 'Turbo Sound Next'),
(79, 'es', 'Turbo Sound Next', 'Turbo Sound Next'),
(80, 'en', 'Next-DAC', 'Next-DAC'),
(80, 'ru', 'Next-DAC', 'Next-DAC'),
(80, 'es', 'Next-DAC', 'Next-DAC'),
(81, 'en', 'General Sound', 'GS'),
(81, 'ru', 'General Sound', 'GS'),
(81, 'es', 'General Sound', 'GS'),
(82, 'en', 'NeoGS', 'NeoGS'),
(82, 'ru', 'NeoGS', 'NeoGS'),
(82, 'es', 'NeoGS', 'NeoGS'),
(83, 'en', 'Covox (#FB)', 'CVX#FB'),
(83, 'ru', 'Covox (#FB)', 'CVX#FB'),
(83, 'es', 'Covox (#FB)', 'CVX#FB'),
(84, 'en', 'Covox (#DD)', 'CVX#DD'),
(84, 'ru', 'Covox (#DD)', 'CVX#DD'),
(84, 'es', 'Covox (#DD)', 'CVX#DD'),
(85, 'en', 'Covox (GS)', 'Covox (GS)'),
(85, 'ru', 'Covox (GS)', 'Covox (GS)'),
(85, 'es', 'Covox (GS)', 'Covox (GS)'),
(86, 'en', 'Soundrive', 'Soundrive'),
(86, 'ru', 'Soundrive', 'Soundrive'),
(86, 'es', 'Soundrive', 'Soundrive'),
(87, 'en', 'Cheetah SpecDrum', 'Cheetah SpecDrum'),
(87, 'ru', 'Cheetah SpecDrum', 'Cheetah SpecDrum'),
(87, 'es', 'Cheetah SpecDrum', 'Cheetah SpecDrum'),
(88, 'en', 'Cheetah Sound Sampler', 'Cheetah Sound Sampler'),
(88, 'ru', 'Cheetah Sound Sampler', 'Cheetah Sound Sampler'),
(88, 'es', 'Cheetah Sound Sampler', 'Cheetah Sound Sampler'),
(89, 'en', 'DMA Ultrasound Card', 'DMA Ultrasound Card'),
(89, 'ru', 'DMA Ultrasound Card', 'DMA Ultrasound Card'),
(89, 'es', 'DMA Ultrasound Card', 'DMA Ultrasound Card'),
(90, 'en', 'Philips SAA 1099', 'Philips SAA 1099'),
(90, 'ru', 'Philips SAA 1099', 'Philips SAA 1099'),
(90, 'es', 'Philips SAA 1099', 'Philips SAA 1099'),
(91, 'en', 'ZXM-MoonSound', 'ZXM-MoonSound'),
(91, 'ru', 'ZXM-MoonSound', 'ZXM-MoonSound'),
(91, 'es', 'ZXM-MoonSound', 'ZXM-MoonSound'),
(92, 'en', 'SID', 'SID'),
(92, 'ru', 'SID', 'SID'),
(92, 'es', 'SID', 'SID'),
(93, 'en', 'SID (eZX/MB)', 'SID (eZX/MB)'),
(93, 'ru', 'SID (eZX/MB)', 'SID (eZX/MB)'),
(93, 'es', 'SID (eZX/MB)', 'SID (eZX/MB)'),
(94, 'en', 'Quazar Surround', 'Quazar Surround'),
(94, 'ru', 'Quazar Surround', 'Quazar Surround'),
(94, 'es', 'Quazar Surround', 'Quazar Surround'),
(95, 'en', 'MIDI', 'MIDI'),
(95, 'ru', 'MIDI', 'MIDI'),
(95, 'es', 'MIDI', 'MIDI'),
(96, 'en', 'Cursor', 'Cursor'),
(96, 'ru', 'Курсор', 'Курсор'),
(96, 'es', 'Cursor', 'Cursor'),
(97, 'en', 'Kempston joystick', 'Kemp.'),
(97, 'ru', 'Кемпстон джойстик', 'Кемп.'),
(97, 'es', 'Joystick kempston', 'Kemp.'),
(98, 'en', 'Kempston 8bit', 'KJ8'),
(98, 'ru', 'Кемпстон 8бит', 'КДЖ8'),
(98, 'es', 'Kempston 8bit', 'KJ8'),
(99, 'en', 'Interface2 joystick (left)', 'Int2'),
(99, 'ru', 'Интерфейс2 джойстик (левый)', 'Int2'),
(99, 'es', 'Joystick Interface2 (izquierdo)', 'Int2'),
(100, 'en', 'Interface2 joystick (right)', 'Int2'),
(100, 'ru', 'Интерфейс2 джойстик (правый)', 'Инт2'),
(100, 'es', 'Joystick Interface2 (derecho)', 'Int2'),
(101, 'en', 'Kempston mouse', 'KM'),
(101, 'ru', 'Кемпстон мышь', 'КМ'),
(101, 'es', 'Ratón kempston', 'KM'),
(102, 'en', 'AY mouse', 'AM'),
(102, 'ru', 'AY мышь', 'AM'),
(102, 'es', 'AY ratón', 'AM'),
(103, 'en', 'Amiga mouse', 'Amiga mouse'),
(103, 'ru', 'Amiga мышь', 'Amiga мышь'),
(103, 'es', 'Amiga ratón', 'Amiga ratón'),
(104, 'en', 'Atari mouse', 'Atari mouse'),
(104, 'ru', 'Atari мышь', 'Atari мышь'),
(104, 'es', 'Atari ratón', 'Atari ratón'),
(105, 'en', 'AMX-Mouse', 'AMX'),
(105, 'ru', 'AMX-Мышь', 'AMX'),
(105, 'es', 'AMX-Ratón', 'AMX'),
(106, 'en', 'Sam mouse', 'Sam mouse'),
(106, 'ru', 'Sam мышь', 'Sam мышь'),
(106, 'es', 'Sam ratón', 'Sam ratón'),
(107, 'en', 'Gun Stick', 'Gun Stick'),
(107, 'ru', 'Gun Stick', 'Gun Stick'),
(107, 'es', 'Gun Stick', 'Gun Stick'),
(108, 'en', 'Magnum Light Phaser', 'Magnum Light Phaser'),
(108, 'ru', 'Magnum Light Phaser', 'Magnum Light Phaser'),
(108, 'es', 'Magnum Light Phaser', 'Magnum Light Phaser'),
(109, 'en', 'Light gun "Novina"', 'Light gun "Novina"'),
(109, 'ru', 'Световой пистолет "Новина"', 'Световой пистолет "Новина"'),
(109, 'es', 'Pistola ligera "Novina"', 'Pistola ligera "Novina"'),
(110, 'en', 'Light pen', 'Light pen'),
(110, 'ru', 'Световое перо', 'Световое перо'),
(110, 'es', 'Lápiz óptico', 'Lápiz óptico'),
(111, 'en', 'Defender Light Gun', 'Defender Light Gun'),
(111, 'ru', 'Defender Light Gun', 'Defender Light Gun'),
(111, 'es', 'Defender Light Gun', 'Defender Light Gun'),
(112, 'en', 'ZXpand interface for ZX81', 'ZXpand interface for ZX81'),
(112, 'ru', 'Интерфейс ZXpand для ZX81', 'Интерфейс ZXpand для ZX81'),
(112, 'es', 'Interfaz ZXpand para ZX81', 'Interfaz ZXpand para ZX81'),
(113, 'en', 'Cache (Shadow RAM)', 'Cache (Shadow RAM)'),
(113, 'ru', 'Кэш (теневое ОЗУ)', 'Кэш (теневое ОЗУ)'),
(113, 'es', 'Caché (Shadow RAM)', 'Caché (Shadow RAM)'),
(114, 'en', 'GMX', 'GMX'),
(114, 'ru', 'GMX', 'GMX'),
(114, 'es', 'GMX', 'GMX'),
(115, 'en', 'Flash color', 'Flash'),
(115, 'ru', 'Flash color', 'Flash'),
(115, 'es', 'Flash color', 'Flash'),
(116, 'en', 'ULAplus', 'ULA+'),
(116, 'ru', 'ULAplus', 'ULA+'),
(116, 'es', 'ULAplus', 'ULA+'),
(117, 'en', 'Radastan video mode', 'Radastan'),
(117, 'ru', 'Radastan (видеорежим)', 'Radastan'),
(117, 'es', 'Modo de vídeo Radastan', 'Radastan'),
(118, 'en', 'DMA', 'DMA'),
(118, 'ru', 'DMA', 'DMA'),
(118, 'es', 'DMA', 'DMA'),
(119, 'en', 'Chroma 80/81', 'Chroma 81'),
(119, 'ru', 'Chroma 80/81', 'Chroma 81'),
(119, 'es', 'Chroma 80/81', 'Chroma 81'),
(120, 'en', 'Trinity Ethernet Interface', 'Trinity Ethernet Interface'),
(120, 'ru', 'Trinity Ethernet Interface', 'Trinity Ethernet Interface'),
(120, 'es', 'Trinity Ethernet Interface', 'Trinity Ethernet Interface'),
(121, 'en', 'Hires', 'Hires'),
(121, 'ru', 'Hires', 'Hires'),
(121, 'es', 'Hires', 'Hires'),
(122, 'en', 'HGFX', 'HGFX'),
(122, 'ru', 'HGFX', 'HGFX'),
(122, 'es', 'HGFX', 'HGFX');

-- Step 3: normalize the link table to ids -------------------------------------
ALTER TABLE `engine_module_zxrelease_hw_required` ENGINE = InnoDB;

ALTER TABLE `engine_module_zxrelease_hw_required`
    ADD COLUMN `hardwareId` INT UNSIGNED NOT NULL DEFAULT 0 AFTER `elementId`;

UPDATE `engine_module_zxrelease_hw_required` `l`
    JOIN `engine_hardware` `h` ON `h`.`code` = `l`.`value`
SET `l`.`hardwareId` = `h`.`id`;

-- GATE: the next statement must return 0. A non-zero count means some stored
-- code is missing from the seed above; STOP and add it, or DROP COLUMN below
-- destroys it.
SELECT COUNT(*) AS `unmapped_rows_must_be_zero` FROM `engine_module_zxrelease_hw_required` WHERE `hardwareId` = 0;

ALTER TABLE `engine_module_zxrelease_hw_required`
    DROP KEY `elementId`,
    DROP COLUMN `value`,
    ADD UNIQUE KEY `elementId` (`elementId`, `hardwareId`),
    ADD KEY `hardwareId` (`hardwareId`),
    ADD CONSTRAINT `zxrelease_hw_hardware` FOREIGN KEY (`hardwareId`) REFERENCES `engine_hardware` (`id`);

-- Step 4: privilege ------------------------------------------------------------
-- `editHardware` on the public root for the catalogue managers group: the
-- hardware list is catalogue upkeep, and that group is who maintains it.
--
-- Two notes for whoever revisits this:
--  * privilegesManager reads $user->privileges from the session, so a user who is
--    logged in when this runs only sees the new section after re-logging in;
--  * the privilege only resolves for users who may `show` the public root, which
--    in practice means membership in `public_visitors` — every real account has it.
INSERT INTO `engine_privilege_relations` (`privilegeId`, `elementId`, `type`, `userId`, `module`, `action`)
SELECT 0, `root`.`id`, 1, `grp`.`id`, 'root', 'editHardware'
FROM `engine_structure_elements` `root`
         JOIN `engine_structure_elements` `grp`
              ON `grp`.`structureType` = 'userGroup' AND `grp`.`structureName` = 'catalogues-managers'
WHERE `root`.`marker` = 'public_root'
  AND NOT EXISTS (SELECT 1
                  FROM (SELECT * FROM `engine_privilege_relations`) `existing`
                  WHERE `existing`.`userId` = `grp`.`id`
                    AND `existing`.`elementId` = `root`.`id`
                    AND `existing`.`module` = 'root'
                    AND `existing`.`action` = 'editHardware');
