<?php return [
    'enabledPlugins' => [
        'cms' => 'cms/',
        'homepage' => 'homepage/',
        'project' => 'project/',
    ],
    'publicSessionLifeTime' => 3600,
    'adminSessionLifeTime' => 86400,
    'defaultSessionLifeTime' => 1440,
    'publicTheme' => 'project',
    'rssTheme' => 'projectRss',
    'googleAnalyticsDomain' => 'zxart.ee',
    'googleAnalyticsId' => 'UA-3287749-14',
    'pageAmountProducts' => 10,
    'availablePageAmountProducts' => [20, 30, 50],
    'timeZone' => 'Europe/Tallinn',
    'errorReporting' => E_ERROR,
    'protocol' => 'http://',
    'defaultRootElementId' => '1',
    'rootMarkerPublic' => 'public_root',
    'rootMarkerAdmin' => 'admin_root',
    'ai_key' => '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',
];