import {PreferenceValues} from './preference.dto';

export const DEFAULT_USER_PREFERENCES: Readonly<PreferenceValues> = {
  theme: 'dark',
  homepage_order: 'newProds,newPictures,newTunes,bestNewDemos,bestNewGames,recentParties,bestPicturesOfMonth,bestTunesOfMonth,latestAddedProds,latestAddedReleases,supportProds,unvotedPictures,randomGoodPictures,unvotedTunes,randomGoodTunes',
  homepage_disabled: '',
  homepage_new_prods_limit: '10',
  homepage_new_pictures_limit: '12',
  homepage_new_tunes_limit: '10',
  homepage_best_demos_limit: '10',
  homepage_best_games_limit: '10',
  homepage_recent_parties_limit: '5',
  homepage_best_pictures_month_limit: '12',
  homepage_best_tunes_month_limit: '10',
  homepage_latest_prods_limit: '10',
  homepage_latest_releases_limit: '10',
  homepage_support_prods_limit: '10',
  homepage_unvoted_pictures_limit: '12',
  homepage_random_pictures_limit: '12',
  homepage_unvoted_tunes_limit: '10',
  homepage_random_tunes_limit: '10',
  homepage_new_prods_start_year: '1',
  homepage_new_prods_min_rating: '3.9',
  homepage_best_demos_min_rating: '4',
  homepage_best_games_min_rating: '4',
  picture_mode: 'mix',
  picture_border: '1',
  picture_hidden: '0',
  picture_scale: '3',
  radio_criteria: '{}',
  language: 'eng',
};
