/**
 * ZX picture format codes, mirroring the backend ZxPictureTypesProvider list.
 * Labels come from the `picture-search.format.*` translation keys.
 */
export const ZX_PICTURE_TYPES = [
  'standard',
  'flash',
  'monochrome',
  'tricolor',
  'multicolor',
  'multicolor4',
  'timex81',
  'timexhr',
  'timexhrg',
  'sam2',
  'sam3',
  'sam4',
  'bsc',
  'bsp',
  'bmc4',
  'mlt',
  'mc',
  'gigascreen',
  'mg1',
  'mg2',
  'mg4',
  'mg8',
  'attributes',
  'lowresgs',
  'stellar',
  'chr$',
  'ulaplus',
  'zxevo',
  'sxg',
  'grf',
  'nxi',
  'sl2',
  'specscii',
  's80',
  's81',
  'sca',
] as const;
