<?php

trait HardwareProvider
{
    public function getHardwareList(): array
    {
        return [
            "computers" => [
                'zx48',
                "zx16",
                'zx128',
                "zx128+2",
                "zx128+2b",
                "zx128+3",
                "sinclairql",
                "timex2048",
                "timex2068",
                "atm",
                "atm2",
                "pentagon128",
                "pentagon512",
                "pentagon1024",
                "pentagon2666",
                "profi",
                "scorpion",
                "scorpion1024",
                "byte",
                "zxmphoenix",
                "zxevolution",
                "zxnext",
                "elementzxmb",
                "zxuno",
                "samcoupe",
                "zx80",
                "zx8116",
                "zx811",
                "zx812",
                "zx8132",
                "zx8164",
                "sprinter",
            ],
            "configuration" => [
                'baseconf',
                'tsconf',
            ],
            "storage" => [
                'tape',
                '3dosdisk',
                'betadisk',
                'cd',
                'profiide',
                'nemoide',
                'zcontroller',
                'atmide',
                'divide',
                'divmmc',
                'smuc',
                'sddivmmc',
                'sdz',
                'sdneogs',
            ],
            "dos" => [
                'trdos',
                'isdos',
                'cpm',
                'esxdos',
                'mdos',
                '3dos',
                'nedoos',
            ],
            "sound" => [
                'ay',
                'beeper',
                'ts',
                'tsfm',
                'gs',
                'ngs',
                'covoxfb',
                'covoxdd',
                'soundrive',
                'specdrum',
                'cheetah',
                'dmausc',
                'saa',
                'zxm',
                'sid',
                'sidelzx',
            ],
            "controls" => [
                'cursor',
                'kempston',
                'kempston8b',
                'int2_1',
                'int2_2',
                'kempstonmouse',
                'aymouse',
            ],
            "expansion" => [
                'zxpand',
                'cache',
                'gmx',
                'flashcolor',
                'ulaplus'
            ],
        ];
    }
}