<?php return [
    'minLevel' => 1,
    'minAmount' => 2,
    'allowedElementTypes' => [
        'zxProdCategory',
        'pressArticle',
        'folder',
        'zxProd',
        'zxRelease',
        'letter',
        'author',
        'authorAlias',
        'group',
        'groupAlias',
        'year',
        'party',
        'zxPicture',
        'zxMusic',
        'countriesList',
        'country',
        'city',
        'tag',
    ],
];