<?php return [
    'adminAllowed' => [
        'zxProdCategory',
        'prodArticle',
        'authorMusic',
        'authorPicture',
        'screenshotsSelector',
        'inlayFilesSelector',
        'infoFilesSelector',
        'adFilesSelector',
        'mapFilesSelector',
        'rzx',
    ],
    'publicAllowed' => [
        'authorsCatalogue',
        'groupsCatalogue',
        'partiesCatalogue',
        'softCatalogue',
        'authorMusic',
        'authorPicture',
        'zxProdCategory',
        'tagsList',
        'countries',
        'screenshotsSelector',
        'inlayFilesSelector',
        'infoFilesSelector',
        'adFilesSelector',
        'mapFilesSelector',
        'rzx',
        'prodArticle',
    ],
];