openapi: 3.0.0
info:
  title: ZxArt API
  version: 1.0.0
paths:
  /comments/:
    $ref: 'comments.yaml#/paths/~1comments~1'
  /comments/id:{id}/:
    $ref: 'comments.yaml#/paths/~1comments~1id:{id}~1'
  /radio/?action=next-tune:
    $ref: 'radio.yaml#/paths/~1radio~1?action=next-tune'
  /tunes/?action=play:
    $ref: 'tunes.yaml#/paths/~1tunes~1?action=play'
  /firstpage/?action=catalogueBaseUrls:
    $ref: 'firstpage.yaml#/paths/~1firstpage~1?action=catalogueBaseUrls'
  /userpreferences/:
    $ref: 'user-preferences.yaml#/paths/~1userpreferences~1'
  /menu/:
    $ref: 'menu.yaml#/paths/~1menu~1'
  /backend-links/:
    $ref: 'backend-links.yaml#/paths/~1backend-links~1'
  /tags/:
    $ref: 'tags.yaml#/paths/~1tags~1'
  /element-privileges/:
    $ref: 'element-privileges.yaml#/paths/~1element-privileges~1'
  /prod-details/:
    $ref: 'prod-details.yaml#/paths/~1prod-details~1'
  /prod-releases/:
    $ref: 'prod-releases.yaml#/paths/~1prod-releases~1'
  /prod-screenshots/:
    $ref: 'prod-files.yaml#/paths/~1prod-screenshots~1'
  /prod-inlays/:
    $ref: 'prod-files.yaml#/paths/~1prod-inlays~1'
  /prod-maps/:
    $ref: 'prod-files.yaml#/paths/~1prod-maps~1'
  /prod-rzx/:
    $ref: 'prod-files.yaml#/paths/~1prod-rzx~1'
  /release-screenshots/:
    $ref: 'prod-files.yaml#/paths/~1release-screenshots~1'
  /prod-articles/:
    $ref: 'prod-articles.yaml#/paths/~1prod-articles~1'
  /prod-mentions/:
    $ref: 'prod-articles.yaml#/paths/~1prod-mentions~1'
  /prod-compilation-items/:
    $ref: 'prod-related-prods.yaml#/paths/~1prod-compilation-items~1'
  /prod-series-prods/:
    $ref: 'prod-related-prods.yaml#/paths/~1prod-series-prods~1'
  /prod-compilations/:
    $ref: 'prod-related-prods.yaml#/paths/~1prod-compilations~1'
  /prod-series/:
    $ref: 'prod-related-prods.yaml#/paths/~1prod-series~1'
components:
  schemas:
    CommentDto:
      $ref: 'comments.yaml#/components/schemas/CommentDto'
    CommentAuthorDto:
      $ref: 'comments.yaml#/components/schemas/CommentAuthorDto'
    CommentTargetDto:
      $ref: 'comments.yaml#/components/schemas/CommentTargetDto'
    PreferenceDto:
      $ref: 'user-preferences.yaml#/components/schemas/PreferenceDto'
    AuthorDto:
      $ref: 'tunes.yaml#/components/schemas/AuthorDto'
    PartyInfoDto:
      $ref: 'tunes.yaml#/components/schemas/PartyInfoDto'
    TuneDto:
      $ref: 'tunes.yaml#/components/schemas/TuneDto'
    ApiResponseTune:
      $ref: 'tunes.yaml#/components/schemas/ApiResponseTune'
    ApiResponseSuccess:
      $ref: 'tunes.yaml#/components/schemas/ApiResponseSuccess'
    TagItem:
      $ref: 'tags.yaml#/components/schemas/TagItem'
    TagWriteItem:
      $ref: 'tags.yaml#/components/schemas/TagWriteItem'
    TagsPayload:
      $ref: 'tags.yaml#/components/schemas/TagsPayload'
    ProdCorePayload:
      $ref: 'prod-details.yaml#/components/schemas/ProdCorePayload'
    ProdReleasesPayload:
      $ref: 'prod-releases.yaml#/components/schemas/ProdReleasesPayload'
    ProdFile:
      $ref: 'prod-files.yaml#/components/schemas/ProdFile'
    ProdFilesPayload:
      $ref: 'prod-files.yaml#/components/schemas/ProdFilesPayload'
    ProdMapsPayload:
      $ref: 'prod-files.yaml#/components/schemas/ProdMapsPayload'
    PressArticlePreview:
      $ref: 'prod-articles.yaml#/components/schemas/PressArticlePreview'
    PressArticlesPayload:
      $ref: 'prod-articles.yaml#/components/schemas/PressArticlesPayload'
    ProdSummary:
      $ref: 'prod-related-prods.yaml#/components/schemas/ProdSummary'
    ProdSummariesPayload:
      $ref: 'prod-related-prods.yaml#/components/schemas/ProdSummariesPayload'
    ProdSeriesEntry:
      $ref: 'prod-related-prods.yaml#/components/schemas/ProdSeriesEntry'
    ProdSeriesPayload:
      $ref: 'prod-related-prods.yaml#/components/schemas/ProdSeriesPayload'
