openapi: 3.0.0
info:
  title: ZxArt API
  version: 1.0.0
paths:
  /comments/:
    $ref: 'comments.yaml#/paths/~1comments~1'
  /comments/id:{id}/:
    $ref: 'comments.yaml#/paths/~1comments~1id:{id}~1'
  /radio/?action=next-tune:
    $ref: 'radio.yaml#/paths/~1radio~1?action=next-tune'
  /tunes/?action=play:
    $ref: 'tunes.yaml#/paths/~1tunes~1?action=play'
  /firstpage/?action=catalogueBaseUrls:
    $ref: 'firstpage.yaml#/paths/~1firstpage~1?action=catalogueBaseUrls'
  /userpreferences/:
    $ref: 'user-preferences.yaml#/paths/~1userpreferences~1'
components:
  schemas:
    CommentDto:
      $ref: 'comments.yaml#/components/schemas/CommentDto'
    CommentAuthorDto:
      $ref: 'comments.yaml#/components/schemas/CommentAuthorDto'
    CommentTargetDto:
      $ref: 'comments.yaml#/components/schemas/CommentTargetDto'
    PreferenceDto:
      $ref: 'user-preferences.yaml#/components/schemas/PreferenceDto'
    AuthorDto:
      $ref: 'tunes.yaml#/components/schemas/AuthorDto'
    PartyInfoDto:
      $ref: 'tunes.yaml#/components/schemas/PartyInfoDto'
    TuneDto:
      $ref: 'tunes.yaml#/components/schemas/TuneDto'
    ApiResponseTune:
      $ref: 'tunes.yaml#/components/schemas/ApiResponseTune'
    ApiResponseSuccess:
      $ref: 'tunes.yaml#/components/schemas/ApiResponseSuccess'
