openapi: 3.0.0
info:
  title: ZxArt Comments API
  version: 2.0.0
  description: API for managing comments. All endpoints return data directly as the response body (HTTP 200), not wrapped in a responseData envelope.

paths:
  /comments/id:{id}/:
    get:
      summary: Get comments tree for an entity
      description: Returns a hierarchical tree of comments associated with the specified element ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the entity (e.g., picture, music, etc.) to get comments for.
          schema:
            type: integer
      responses:
        '200':
          description: Array of root-level comments with nested children.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /comments/?action=latest:
    get:
      summary: Get latest comments
      description: Returns the most recent comments across all entities, sorted by date descending.
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [latest]
        - name: limit
          in: query
          required: false
          description: Maximum number of comments to return (default 10).
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Array of recent comments.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentDto'
        '500':
          $ref: '#/components/responses/InternalError'

  /comments/?action=list:
    get:
      summary: Get paginated list of all comments
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [list]
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Paginated comments list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentsListDto'
        '500':
          $ref: '#/components/responses/InternalError'

  /comments/:
    post:
      summary: Comment actions (Add, Update, Delete)
      description: Performs actions on comments based on the 'action' parameter. Uses application/x-www-form-urlencoded.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID of the target entity (for 'add') or comment ID (for 'update'/'delete').
                action:
                  type: string
                  enum: [add, update, delete]
                content:
                  type: string
                  description: Comment text (required for 'add' and 'update').
              required:
                - id
                - action
      responses:
        '200':
          description: Created or updated CommentDto (add/update), or null (delete).
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CommentDto'
                  - type: 'null'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    CommentAuthorDto:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
          nullable: true
        badges:
          type: array
          items:
            type: string

    CommentTargetDto:
      type: object
      properties:
        title:
          type: string
        url:
          type: string

    CommentDto:
      type: object
      properties:
        id:
          type: integer
        author:
          $ref: '#/components/schemas/CommentAuthorDto'
          nullable: true
        date:
          type: string
          description: Creation date (formatted)
        content:
          type: string
          description: Decorated HTML content
        originalContent:
          type: string
          description: Original raw content
        canEdit:
          type: boolean
        canDelete:
          type: boolean
        target:
          $ref: '#/components/schemas/CommentTargetDto'
          nullable: true
        parentId:
          type: integer
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/CommentDto'

    CommentsListDto:
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentDto'
        currentPage:
          type: integer
        pagesAmount:
          type: integer
        totalCount:
          type: integer

    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string

  responses:
    BadRequest:
      description: Bad request (missing or invalid parameters, or domain error).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
