openapi: 3.0.0
info:
  title: ZxArt Firstpage API
  version: 2.0.0
  description: API for homepage modules and metadata. All endpoints return the data directly as the response body (HTTP 200), not wrapped in a responseData envelope.

paths:
  /firstpage/?action=catalogueBaseUrls:
    get:
      summary: Get catalogue base URLs for homepage modules
      description: Returns base URLs for prod catalogue, graphics search, and music search in the current language. Cached server-side (Redis, 24h).
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [catalogueBaseUrls]
      responses:
        '200':
          description: Catalogue base URLs.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogueBaseUrlsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    CatalogueBaseUrlsResponse:
      type: object
      properties:
        prodCatalogueBaseUrl:
          type: string
          nullable: true
        graphicsBaseUrl:
          type: string
          nullable: true
        musicBaseUrl:
          type: string
          nullable: true

    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string

  responses:
    BadRequest:
      description: Bad request (e.g. unknown action parameter).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
