openapi: 3.0.0
info:
  title: ZxArt Radio API
  version: 1.0.0
  description: API for radio playback.

paths:
  /radio/?action=next-tune:
    post:
      summary: Get next tune for radio mode
      description: Returns a tune matching the provided criteria or preset.
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [next-tune]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RadioNextTuneRequest'
      responses:
        '200':
          description: A JSON object with responseStatus and responseData.
          content:
            application/json:
              schema:
                $ref: 'tunes.yaml#/components/schemas/ApiResponseTune'
  /radio/?action=options:
    get:
      summary: Get radio filter options
      description: Returns available values for advanced radio filters.
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [options]
      responses:
        '200':
          description: A JSON object with responseStatus and responseData.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRadioOptions'

components:
  schemas:
    RadioNextTuneRequest:
      type: object
      properties:
        preset:
          type: string
          description: Preset id (legacy).
          enum:
            - discover
            - randomgood
            - games
            - demoscene
            - lastyear
            - ay
            - beeper
            - exotic
            - underground
        criteria:
          $ref: '#/components/schemas/RadioCriteria'

    RadioCriteria:
      type: object
      properties:
        minRating:
          type: number
          format: float
        maxRating:
          type: number
          format: float
        yearsInclude:
          type: array
          items:
            type: integer
        yearsExclude:
          type: array
          items:
            type: integer
        countriesInclude:
          type: array
          items:
            type: integer
        countriesExclude:
          type: array
          items:
            type: integer
        formatGroupsInclude:
          type: array
          items:
            type: string
        formatGroupsExclude:
          type: array
          items:
            type: string
        formatsInclude:
          type: array
          items:
            type: string
        formatsExclude:
          type: array
          items:
            type: string
        bestVotesLimit:
          type: integer
        maxPlays:
          type: integer
        minPartyPlace:
          type: integer
        requireGame:
          type: boolean
        hasParty:
          type: boolean
        notVotedByUserId:
          type: integer
    ApiResponseRadioOptions:
      type: object
      properties:
        responseStatus:
          type: string
          enum: [success, error]
        responseData:
          $ref: '#/components/schemas/RadioFilterOptions'
        errorMessage:
          type: string
    RadioFilterOptions:
      type: object
      properties:
        yearRange:
          type: object
          properties:
            min:
              type: integer
              nullable: true
            max:
              type: integer
              nullable: true
        countries:
          type: array
          items:
            $ref: '#/components/schemas/RadioCountryOption'
        formatGroups:
          type: array
          items:
            type: string
        formats:
          type: array
          items:
            type: string
        partyOptions:
          type: array
          items:
            type: string
            enum: [any, yes, no]
    RadioCountryOption:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
